# coding: utf-8

"""
    Metal API

    This is the API for Equinix Metal. The API allows you to programmatically interact with all of your Equinix Metal resources, including devices, networks, addresses, organizations, projects, and your user account.  The official API docs are hosted at <https://metal.equinix.com/developers/api>.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@equinixmetal.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import metal
from models.global_bgp_ranges_api import GlobalBgpRangesApi  # noqa: E501
from metal.rest import ApiException


class TestGlobalBgpRangesApi(unittest.TestCase):
    """GlobalBgpRangesApi unit test stubs"""

    def setUp(self):
        self.api = models.global_bgp_ranges_api.GlobalBgpRangesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_global_bgp_ranges(self):
        """Test case for find_global_bgp_ranges

        Retrieve all global bgp ranges  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
