# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class ActivateHardwareReservationRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, description: str=None):
        """ActivateHardwareReservationRequest - a model defined in OpenAPI

        :param description: The description of this ActivateHardwareReservationRequest.
        """
        self.openapi_types = {
            'description': str
        }

        self.attribute_map = {
            'description': 'description'
        }

        self._description = description

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ActivateHardwareReservationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The activateHardwareReservation_request of this ActivateHardwareReservationRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def description(self):
        """Gets the description of this ActivateHardwareReservationRequest.


        :return: The description of this ActivateHardwareReservationRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ActivateHardwareReservationRequest.


        :param description: The description of this ActivateHardwareReservationRequest.
        :type description: str
        """

        self._description = description
