# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class BondPortData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None):
        """BondPortData - a model defined in OpenAPI

        :param id: The id of this BondPortData.
        :param name: The name of this BondPortData.
        """
        self.openapi_types = {
            'id': str,
            'name': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name'
        }

        self._id = id
        self._name = name

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BondPortData':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BondPortData of this BondPortData.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this BondPortData.

        ID of the bonding port

        :return: The id of this BondPortData.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BondPortData.

        ID of the bonding port

        :param id: The id of this BondPortData.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this BondPortData.

        Name of the port interface for the bond (\"bond0\")

        :return: The name of this BondPortData.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BondPortData.

        Name of the port interface for the bond (\"bond0\")

        :param name: The name of this BondPortData.
        :type name: str
        """

        self._name = name
