# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class DeviceProjectLite(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, href: str=None):
        """DeviceProjectLite - a model defined in OpenAPI

        :param href: The href of this DeviceProjectLite.
        """
        self.openapi_types = {
            'href': str
        }

        self.attribute_map = {
            'href': 'href'
        }

        self._href = href

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DeviceProjectLite':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Device_project_lite of this DeviceProjectLite.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def href(self):
        """Gets the href of this DeviceProjectLite.


        :return: The href of this DeviceProjectLite.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this DeviceProjectLite.


        :param href: The href of this DeviceProjectLite.
        :type href: str
        """
        if href is None:
            raise ValueError("Invalid value for `href`, must not be `None`")

        self._href = href
