# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class IPAvailabilitiesList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, available: List[str]=None):
        """IPAvailabilitiesList - a model defined in OpenAPI

        :param available: The available of this IPAvailabilitiesList.
        """
        self.openapi_types = {
            'available': List[str]
        }

        self.attribute_map = {
            'available': 'available'
        }

        self._available = available

    @classmethod
    def from_dict(cls, dikt: dict) -> 'IPAvailabilitiesList':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The IPAvailabilitiesList of this IPAvailabilitiesList.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def available(self):
        """Gets the available of this IPAvailabilitiesList.


        :return: The available of this IPAvailabilitiesList.
        :rtype: List[str]
        """
        return self._available

    @available.setter
    def available(self, available):
        """Sets the available of this IPAvailabilitiesList.


        :param available: The available of this IPAvailabilitiesList.
        :type available: List[str]
        """

        self._available = available
