# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal.types.metadata_network_network_bonding import MetadataNetworkNetworkBonding
from metal import util


class MetadataNetworkNetwork(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, bonding: MetadataNetworkNetworkBonding=None):
        """MetadataNetworkNetwork - a model defined in OpenAPI

        :param bonding: The bonding of this MetadataNetworkNetwork.
        """
        self.openapi_types = {
            'bonding': MetadataNetworkNetworkBonding
        }

        self.attribute_map = {
            'bonding': 'bonding'
        }

        self._bonding = bonding

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MetadataNetworkNetwork':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Metadata_network_network of this MetadataNetworkNetwork.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bonding(self):
        """Gets the bonding of this MetadataNetworkNetwork.


        :return: The bonding of this MetadataNetworkNetwork.
        :rtype: MetadataNetworkNetworkBonding
        """
        return self._bonding

    @bonding.setter
    def bonding(self, bonding):
        """Sets the bonding of this MetadataNetworkNetwork.


        :param bonding: The bonding of this MetadataNetworkNetwork.
        :type bonding: MetadataNetworkNetworkBonding
        """

        self._bonding = bonding
