# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal.types.payment_method import PaymentMethod
from metal import util


class PaymentMethodList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, payment_methods: List[PaymentMethod]=None):
        """PaymentMethodList - a model defined in OpenAPI

        :param payment_methods: The payment_methods of this PaymentMethodList.
        """
        self.openapi_types = {
            'payment_methods': List[PaymentMethod]
        }

        self.attribute_map = {
            'payment_methods': 'payment_methods'
        }

        self._payment_methods = payment_methods

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PaymentMethodList':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PaymentMethodList of this PaymentMethodList.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def payment_methods(self):
        """Gets the payment_methods of this PaymentMethodList.


        :return: The payment_methods of this PaymentMethodList.
        :rtype: List[PaymentMethod]
        """
        return self._payment_methods

    @payment_methods.setter
    def payment_methods(self, payment_methods):
        """Sets the payment_methods of this PaymentMethodList.


        :param payment_methods: The payment_methods of this PaymentMethodList.
        :type payment_methods: List[PaymentMethod]
        """

        self._payment_methods = payment_methods
