# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class PaymentMethodUpdateInput(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, billing_address: object=None, cardholder_name: str=None, default: bool=None, expiration_month: str=None, expiration_year: int=None, name: str=None):
        """PaymentMethodUpdateInput - a model defined in OpenAPI

        :param billing_address: The billing_address of this PaymentMethodUpdateInput.
        :param cardholder_name: The cardholder_name of this PaymentMethodUpdateInput.
        :param default: The default of this PaymentMethodUpdateInput.
        :param expiration_month: The expiration_month of this PaymentMethodUpdateInput.
        :param expiration_year: The expiration_year of this PaymentMethodUpdateInput.
        :param name: The name of this PaymentMethodUpdateInput.
        """
        self.openapi_types = {
            'billing_address': object,
            'cardholder_name': str,
            'default': bool,
            'expiration_month': str,
            'expiration_year': int,
            'name': str
        }

        self.attribute_map = {
            'billing_address': 'billing_address',
            'cardholder_name': 'cardholder_name',
            'default': 'default',
            'expiration_month': 'expiration_month',
            'expiration_year': 'expiration_year',
            'name': 'name'
        }

        self._billing_address = billing_address
        self._cardholder_name = cardholder_name
        self._default = default
        self._expiration_month = expiration_month
        self._expiration_year = expiration_year
        self._name = name

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PaymentMethodUpdateInput':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PaymentMethodUpdateInput of this PaymentMethodUpdateInput.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def billing_address(self):
        """Gets the billing_address of this PaymentMethodUpdateInput.


        :return: The billing_address of this PaymentMethodUpdateInput.
        :rtype: object
        """
        return self._billing_address

    @billing_address.setter
    def billing_address(self, billing_address):
        """Sets the billing_address of this PaymentMethodUpdateInput.


        :param billing_address: The billing_address of this PaymentMethodUpdateInput.
        :type billing_address: object
        """

        self._billing_address = billing_address

    @property
    def cardholder_name(self):
        """Gets the cardholder_name of this PaymentMethodUpdateInput.


        :return: The cardholder_name of this PaymentMethodUpdateInput.
        :rtype: str
        """
        return self._cardholder_name

    @cardholder_name.setter
    def cardholder_name(self, cardholder_name):
        """Sets the cardholder_name of this PaymentMethodUpdateInput.


        :param cardholder_name: The cardholder_name of this PaymentMethodUpdateInput.
        :type cardholder_name: str
        """

        self._cardholder_name = cardholder_name

    @property
    def default(self):
        """Gets the default of this PaymentMethodUpdateInput.


        :return: The default of this PaymentMethodUpdateInput.
        :rtype: bool
        """
        return self._default

    @default.setter
    def default(self, default):
        """Sets the default of this PaymentMethodUpdateInput.


        :param default: The default of this PaymentMethodUpdateInput.
        :type default: bool
        """

        self._default = default

    @property
    def expiration_month(self):
        """Gets the expiration_month of this PaymentMethodUpdateInput.


        :return: The expiration_month of this PaymentMethodUpdateInput.
        :rtype: str
        """
        return self._expiration_month

    @expiration_month.setter
    def expiration_month(self, expiration_month):
        """Sets the expiration_month of this PaymentMethodUpdateInput.


        :param expiration_month: The expiration_month of this PaymentMethodUpdateInput.
        :type expiration_month: str
        """

        self._expiration_month = expiration_month

    @property
    def expiration_year(self):
        """Gets the expiration_year of this PaymentMethodUpdateInput.


        :return: The expiration_year of this PaymentMethodUpdateInput.
        :rtype: int
        """
        return self._expiration_year

    @expiration_year.setter
    def expiration_year(self, expiration_year):
        """Sets the expiration_year of this PaymentMethodUpdateInput.


        :param expiration_year: The expiration_year of this PaymentMethodUpdateInput.
        :type expiration_year: int
        """

        self._expiration_year = expiration_year

    @property
    def name(self):
        """Gets the name of this PaymentMethodUpdateInput.


        :return: The name of this PaymentMethodUpdateInput.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PaymentMethodUpdateInput.


        :param name: The name of this PaymentMethodUpdateInput.
        :type name: str
        """

        self._name = name
