# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal.types.plan_available_in_inner_price import PlanAvailableInInnerPrice
from metal import util


class PlanAvailableInMetrosInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, href: str=None, price: PlanAvailableInInnerPrice=None):
        """PlanAvailableInMetrosInner - a model defined in OpenAPI

        :param href: The href of this PlanAvailableInMetrosInner.
        :param price: The price of this PlanAvailableInMetrosInner.
        """
        self.openapi_types = {
            'href': str,
            'price': PlanAvailableInInnerPrice
        }

        self.attribute_map = {
            'href': 'href',
            'price': 'price'
        }

        self._href = href
        self._price = price

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PlanAvailableInMetrosInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Plan_available_in_metros_inner of this PlanAvailableInMetrosInner.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def href(self):
        """Gets the href of this PlanAvailableInMetrosInner.

        href to the Metro

        :return: The href of this PlanAvailableInMetrosInner.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """Sets the href of this PlanAvailableInMetrosInner.

        href to the Metro

        :param href: The href of this PlanAvailableInMetrosInner.
        :type href: str
        """

        self._href = href

    @property
    def price(self):
        """Gets the price of this PlanAvailableInMetrosInner.


        :return: The price of this PlanAvailableInMetrosInner.
        :rtype: PlanAvailableInInnerPrice
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this PlanAvailableInMetrosInner.


        :param price: The price of this PlanAvailableInMetrosInner.
        :type price: PlanAvailableInInnerPrice
        """

        self._price = price
