# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class PortConvertLayer3InputRequestIpsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, address_family: int=None, public: bool=None):
        """PortConvertLayer3InputRequestIpsInner - a model defined in OpenAPI

        :param address_family: The address_family of this PortConvertLayer3InputRequestIpsInner.
        :param public: The public of this PortConvertLayer3InputRequestIpsInner.
        """
        self.openapi_types = {
            'address_family': int,
            'public': bool
        }

        self.attribute_map = {
            'address_family': 'address_family',
            'public': 'public'
        }

        self._address_family = address_family
        self._public = public

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PortConvertLayer3InputRequestIpsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PortConvertLayer3Input_request_ips_inner of this PortConvertLayer3InputRequestIpsInner.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def address_family(self):
        """Gets the address_family of this PortConvertLayer3InputRequestIpsInner.


        :return: The address_family of this PortConvertLayer3InputRequestIpsInner.
        :rtype: int
        """
        return self._address_family

    @address_family.setter
    def address_family(self, address_family):
        """Sets the address_family of this PortConvertLayer3InputRequestIpsInner.


        :param address_family: The address_family of this PortConvertLayer3InputRequestIpsInner.
        :type address_family: int
        """

        self._address_family = address_family

    @property
    def public(self):
        """Gets the public of this PortConvertLayer3InputRequestIpsInner.


        :return: The public of this PortConvertLayer3InputRequestIpsInner.
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this PortConvertLayer3InputRequestIpsInner.


        :param public: The public of this PortConvertLayer3InputRequestIpsInner.
        :type public: bool
        """

        self._public = public
