# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class RecoveryCodeList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, recovery_codes: List[str]=None):
        """RecoveryCodeList - a model defined in OpenAPI

        :param recovery_codes: The recovery_codes of this RecoveryCodeList.
        """
        self.openapi_types = {
            'recovery_codes': List[str]
        }

        self.attribute_map = {
            'recovery_codes': 'recovery_codes'
        }

        self._recovery_codes = recovery_codes

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RecoveryCodeList':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RecoveryCodeList of this RecoveryCodeList.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def recovery_codes(self):
        """Gets the recovery_codes of this RecoveryCodeList.


        :return: The recovery_codes of this RecoveryCodeList.
        :rtype: List[str]
        """
        return self._recovery_codes

    @recovery_codes.setter
    def recovery_codes(self, recovery_codes):
        """Sets the recovery_codes of this RecoveryCodeList.


        :param recovery_codes: The recovery_codes of this RecoveryCodeList.
        :type recovery_codes: List[str]
        """

        self._recovery_codes = recovery_codes
