# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class SelfServiceReservationItemResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amount: float=None, id: str=None, metro_code: str=None, metro_id: str=None, metro_name: str=None, plan_id: str=None, plan_name: str=None, plan_slug: str=None, quantity: int=None, term: str=None):
        """SelfServiceReservationItemResponse - a model defined in OpenAPI

        :param amount: The amount of this SelfServiceReservationItemResponse.
        :param id: The id of this SelfServiceReservationItemResponse.
        :param metro_code: The metro_code of this SelfServiceReservationItemResponse.
        :param metro_id: The metro_id of this SelfServiceReservationItemResponse.
        :param metro_name: The metro_name of this SelfServiceReservationItemResponse.
        :param plan_id: The plan_id of this SelfServiceReservationItemResponse.
        :param plan_name: The plan_name of this SelfServiceReservationItemResponse.
        :param plan_slug: The plan_slug of this SelfServiceReservationItemResponse.
        :param quantity: The quantity of this SelfServiceReservationItemResponse.
        :param term: The term of this SelfServiceReservationItemResponse.
        """
        self.openapi_types = {
            'amount': float,
            'id': str,
            'metro_code': str,
            'metro_id': str,
            'metro_name': str,
            'plan_id': str,
            'plan_name': str,
            'plan_slug': str,
            'quantity': int,
            'term': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'id': 'id',
            'metro_code': 'metro_code',
            'metro_id': 'metro_id',
            'metro_name': 'metro_name',
            'plan_id': 'plan_id',
            'plan_name': 'plan_name',
            'plan_slug': 'plan_slug',
            'quantity': 'quantity',
            'term': 'term'
        }

        self._amount = amount
        self._id = id
        self._metro_code = metro_code
        self._metro_id = metro_id
        self._metro_name = metro_name
        self._plan_id = plan_id
        self._plan_name = plan_name
        self._plan_slug = plan_slug
        self._quantity = quantity
        self._term = term

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SelfServiceReservationItemResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SelfServiceReservationItemResponse of this SelfServiceReservationItemResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self):
        """Gets the amount of this SelfServiceReservationItemResponse.


        :return: The amount of this SelfServiceReservationItemResponse.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this SelfServiceReservationItemResponse.


        :param amount: The amount of this SelfServiceReservationItemResponse.
        :type amount: float
        """

        self._amount = amount

    @property
    def id(self):
        """Gets the id of this SelfServiceReservationItemResponse.


        :return: The id of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SelfServiceReservationItemResponse.


        :param id: The id of this SelfServiceReservationItemResponse.
        :type id: str
        """

        self._id = id

    @property
    def metro_code(self):
        """Gets the metro_code of this SelfServiceReservationItemResponse.


        :return: The metro_code of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._metro_code

    @metro_code.setter
    def metro_code(self, metro_code):
        """Sets the metro_code of this SelfServiceReservationItemResponse.


        :param metro_code: The metro_code of this SelfServiceReservationItemResponse.
        :type metro_code: str
        """

        self._metro_code = metro_code

    @property
    def metro_id(self):
        """Gets the metro_id of this SelfServiceReservationItemResponse.


        :return: The metro_id of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._metro_id

    @metro_id.setter
    def metro_id(self, metro_id):
        """Sets the metro_id of this SelfServiceReservationItemResponse.


        :param metro_id: The metro_id of this SelfServiceReservationItemResponse.
        :type metro_id: str
        """

        self._metro_id = metro_id

    @property
    def metro_name(self):
        """Gets the metro_name of this SelfServiceReservationItemResponse.


        :return: The metro_name of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._metro_name

    @metro_name.setter
    def metro_name(self, metro_name):
        """Sets the metro_name of this SelfServiceReservationItemResponse.


        :param metro_name: The metro_name of this SelfServiceReservationItemResponse.
        :type metro_name: str
        """

        self._metro_name = metro_name

    @property
    def plan_id(self):
        """Gets the plan_id of this SelfServiceReservationItemResponse.


        :return: The plan_id of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._plan_id

    @plan_id.setter
    def plan_id(self, plan_id):
        """Sets the plan_id of this SelfServiceReservationItemResponse.


        :param plan_id: The plan_id of this SelfServiceReservationItemResponse.
        :type plan_id: str
        """

        self._plan_id = plan_id

    @property
    def plan_name(self):
        """Gets the plan_name of this SelfServiceReservationItemResponse.


        :return: The plan_name of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._plan_name

    @plan_name.setter
    def plan_name(self, plan_name):
        """Sets the plan_name of this SelfServiceReservationItemResponse.


        :param plan_name: The plan_name of this SelfServiceReservationItemResponse.
        :type plan_name: str
        """

        self._plan_name = plan_name

    @property
    def plan_slug(self):
        """Gets the plan_slug of this SelfServiceReservationItemResponse.


        :return: The plan_slug of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._plan_slug

    @plan_slug.setter
    def plan_slug(self, plan_slug):
        """Sets the plan_slug of this SelfServiceReservationItemResponse.


        :param plan_slug: The plan_slug of this SelfServiceReservationItemResponse.
        :type plan_slug: str
        """

        self._plan_slug = plan_slug

    @property
    def quantity(self):
        """Gets the quantity of this SelfServiceReservationItemResponse.


        :return: The quantity of this SelfServiceReservationItemResponse.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this SelfServiceReservationItemResponse.


        :param quantity: The quantity of this SelfServiceReservationItemResponse.
        :type quantity: int
        """

        self._quantity = quantity

    @property
    def term(self):
        """Gets the term of this SelfServiceReservationItemResponse.


        :return: The term of this SelfServiceReservationItemResponse.
        :rtype: str
        """
        return self._term

    @term.setter
    def term(self, term):
        """Sets the term of this SelfServiceReservationItemResponse.


        :param term: The term of this SelfServiceReservationItemResponse.
        :type term: str
        """

        self._term = term
