# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal import util


class SpotMarketRequestCreateInputInstanceAttributes(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, always_pxe: bool=None, billing_cycle: str=None, customdata: object=None, description: str=None, features: List[str]=None, hostname: str=None, hostnames: List[str]=None, locked: bool=None, no_ssh_keys: bool=None, operating_system: str=None, plan: str=None, private_ipv4_subnet_size: int=None, project_ssh_keys: List[str]=None, public_ipv4_subnet_size: int=None, tags: List[str]=None, termination_time: datetime=None, user_ssh_keys: List[str]=None, userdata: str=None):
        """SpotMarketRequestCreateInputInstanceAttributes - a model defined in OpenAPI

        :param always_pxe: The always_pxe of this SpotMarketRequestCreateInputInstanceAttributes.
        :param billing_cycle: The billing_cycle of this SpotMarketRequestCreateInputInstanceAttributes.
        :param customdata: The customdata of this SpotMarketRequestCreateInputInstanceAttributes.
        :param description: The description of this SpotMarketRequestCreateInputInstanceAttributes.
        :param features: The features of this SpotMarketRequestCreateInputInstanceAttributes.
        :param hostname: The hostname of this SpotMarketRequestCreateInputInstanceAttributes.
        :param hostnames: The hostnames of this SpotMarketRequestCreateInputInstanceAttributes.
        :param locked: The locked of this SpotMarketRequestCreateInputInstanceAttributes.
        :param no_ssh_keys: The no_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :param operating_system: The operating_system of this SpotMarketRequestCreateInputInstanceAttributes.
        :param plan: The plan of this SpotMarketRequestCreateInputInstanceAttributes.
        :param private_ipv4_subnet_size: The private_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.
        :param project_ssh_keys: The project_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :param public_ipv4_subnet_size: The public_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.
        :param tags: The tags of this SpotMarketRequestCreateInputInstanceAttributes.
        :param termination_time: The termination_time of this SpotMarketRequestCreateInputInstanceAttributes.
        :param user_ssh_keys: The user_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :param userdata: The userdata of this SpotMarketRequestCreateInputInstanceAttributes.
        """
        self.openapi_types = {
            'always_pxe': bool,
            'billing_cycle': str,
            'customdata': object,
            'description': str,
            'features': List[str],
            'hostname': str,
            'hostnames': List[str],
            'locked': bool,
            'no_ssh_keys': bool,
            'operating_system': str,
            'plan': str,
            'private_ipv4_subnet_size': int,
            'project_ssh_keys': List[str],
            'public_ipv4_subnet_size': int,
            'tags': List[str],
            'termination_time': datetime,
            'user_ssh_keys': List[str],
            'userdata': str
        }

        self.attribute_map = {
            'always_pxe': 'always_pxe',
            'billing_cycle': 'billing_cycle',
            'customdata': 'customdata',
            'description': 'description',
            'features': 'features',
            'hostname': 'hostname',
            'hostnames': 'hostnames',
            'locked': 'locked',
            'no_ssh_keys': 'no_ssh_keys',
            'operating_system': 'operating_system',
            'plan': 'plan',
            'private_ipv4_subnet_size': 'private_ipv4_subnet_size',
            'project_ssh_keys': 'project_ssh_keys',
            'public_ipv4_subnet_size': 'public_ipv4_subnet_size',
            'tags': 'tags',
            'termination_time': 'termination_time',
            'user_ssh_keys': 'user_ssh_keys',
            'userdata': 'userdata'
        }

        self._always_pxe = always_pxe
        self._billing_cycle = billing_cycle
        self._customdata = customdata
        self._description = description
        self._features = features
        self._hostname = hostname
        self._hostnames = hostnames
        self._locked = locked
        self._no_ssh_keys = no_ssh_keys
        self._operating_system = operating_system
        self._plan = plan
        self._private_ipv4_subnet_size = private_ipv4_subnet_size
        self._project_ssh_keys = project_ssh_keys
        self._public_ipv4_subnet_size = public_ipv4_subnet_size
        self._tags = tags
        self._termination_time = termination_time
        self._user_ssh_keys = user_ssh_keys
        self._userdata = userdata

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SpotMarketRequestCreateInputInstanceAttributes':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SpotMarketRequestCreateInput_instance_attributes of this SpotMarketRequestCreateInputInstanceAttributes.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def always_pxe(self):
        """Gets the always_pxe of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The always_pxe of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: bool
        """
        return self._always_pxe

    @always_pxe.setter
    def always_pxe(self, always_pxe):
        """Sets the always_pxe of this SpotMarketRequestCreateInputInstanceAttributes.


        :param always_pxe: The always_pxe of this SpotMarketRequestCreateInputInstanceAttributes.
        :type always_pxe: bool
        """

        self._always_pxe = always_pxe

    @property
    def billing_cycle(self):
        """Gets the billing_cycle of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The billing_cycle of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: str
        """
        return self._billing_cycle

    @billing_cycle.setter
    def billing_cycle(self, billing_cycle):
        """Sets the billing_cycle of this SpotMarketRequestCreateInputInstanceAttributes.


        :param billing_cycle: The billing_cycle of this SpotMarketRequestCreateInputInstanceAttributes.
        :type billing_cycle: str
        """

        self._billing_cycle = billing_cycle

    @property
    def customdata(self):
        """Gets the customdata of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The customdata of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: object
        """
        return self._customdata

    @customdata.setter
    def customdata(self, customdata):
        """Sets the customdata of this SpotMarketRequestCreateInputInstanceAttributes.


        :param customdata: The customdata of this SpotMarketRequestCreateInputInstanceAttributes.
        :type customdata: object
        """

        self._customdata = customdata

    @property
    def description(self):
        """Gets the description of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The description of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this SpotMarketRequestCreateInputInstanceAttributes.


        :param description: The description of this SpotMarketRequestCreateInputInstanceAttributes.
        :type description: str
        """

        self._description = description

    @property
    def features(self):
        """Gets the features of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The features of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: List[str]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this SpotMarketRequestCreateInputInstanceAttributes.


        :param features: The features of this SpotMarketRequestCreateInputInstanceAttributes.
        :type features: List[str]
        """

        self._features = features

    @property
    def hostname(self):
        """Gets the hostname of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The hostname of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: str
        """
        return self._hostname

    @hostname.setter
    def hostname(self, hostname):
        """Sets the hostname of this SpotMarketRequestCreateInputInstanceAttributes.


        :param hostname: The hostname of this SpotMarketRequestCreateInputInstanceAttributes.
        :type hostname: str
        """

        self._hostname = hostname

    @property
    def hostnames(self):
        """Gets the hostnames of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The hostnames of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: List[str]
        """
        return self._hostnames

    @hostnames.setter
    def hostnames(self, hostnames):
        """Sets the hostnames of this SpotMarketRequestCreateInputInstanceAttributes.


        :param hostnames: The hostnames of this SpotMarketRequestCreateInputInstanceAttributes.
        :type hostnames: List[str]
        """

        self._hostnames = hostnames

    @property
    def locked(self):
        """Gets the locked of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The locked of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: bool
        """
        return self._locked

    @locked.setter
    def locked(self, locked):
        """Sets the locked of this SpotMarketRequestCreateInputInstanceAttributes.


        :param locked: The locked of this SpotMarketRequestCreateInputInstanceAttributes.
        :type locked: bool
        """

        self._locked = locked

    @property
    def no_ssh_keys(self):
        """Gets the no_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The no_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: bool
        """
        return self._no_ssh_keys

    @no_ssh_keys.setter
    def no_ssh_keys(self, no_ssh_keys):
        """Sets the no_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.


        :param no_ssh_keys: The no_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :type no_ssh_keys: bool
        """

        self._no_ssh_keys = no_ssh_keys

    @property
    def operating_system(self):
        """Gets the operating_system of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The operating_system of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: str
        """
        return self._operating_system

    @operating_system.setter
    def operating_system(self, operating_system):
        """Sets the operating_system of this SpotMarketRequestCreateInputInstanceAttributes.


        :param operating_system: The operating_system of this SpotMarketRequestCreateInputInstanceAttributes.
        :type operating_system: str
        """

        self._operating_system = operating_system

    @property
    def plan(self):
        """Gets the plan of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The plan of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: str
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this SpotMarketRequestCreateInputInstanceAttributes.


        :param plan: The plan of this SpotMarketRequestCreateInputInstanceAttributes.
        :type plan: str
        """

        self._plan = plan

    @property
    def private_ipv4_subnet_size(self):
        """Gets the private_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The private_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: int
        """
        return self._private_ipv4_subnet_size

    @private_ipv4_subnet_size.setter
    def private_ipv4_subnet_size(self, private_ipv4_subnet_size):
        """Sets the private_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.


        :param private_ipv4_subnet_size: The private_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.
        :type private_ipv4_subnet_size: int
        """

        self._private_ipv4_subnet_size = private_ipv4_subnet_size

    @property
    def project_ssh_keys(self):
        """Gets the project_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The project_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: List[str]
        """
        return self._project_ssh_keys

    @project_ssh_keys.setter
    def project_ssh_keys(self, project_ssh_keys):
        """Sets the project_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.


        :param project_ssh_keys: The project_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :type project_ssh_keys: List[str]
        """

        self._project_ssh_keys = project_ssh_keys

    @property
    def public_ipv4_subnet_size(self):
        """Gets the public_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The public_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: int
        """
        return self._public_ipv4_subnet_size

    @public_ipv4_subnet_size.setter
    def public_ipv4_subnet_size(self, public_ipv4_subnet_size):
        """Sets the public_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.


        :param public_ipv4_subnet_size: The public_ipv4_subnet_size of this SpotMarketRequestCreateInputInstanceAttributes.
        :type public_ipv4_subnet_size: int
        """

        self._public_ipv4_subnet_size = public_ipv4_subnet_size

    @property
    def tags(self):
        """Gets the tags of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The tags of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this SpotMarketRequestCreateInputInstanceAttributes.


        :param tags: The tags of this SpotMarketRequestCreateInputInstanceAttributes.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def termination_time(self):
        """Gets the termination_time of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The termination_time of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: datetime
        """
        return self._termination_time

    @termination_time.setter
    def termination_time(self, termination_time):
        """Sets the termination_time of this SpotMarketRequestCreateInputInstanceAttributes.


        :param termination_time: The termination_time of this SpotMarketRequestCreateInputInstanceAttributes.
        :type termination_time: datetime
        """

        self._termination_time = termination_time

    @property
    def user_ssh_keys(self):
        """Gets the user_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.

        The UUIDs of users whose SSH keys should be included on the provisioned device.

        :return: The user_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: List[str]
        """
        return self._user_ssh_keys

    @user_ssh_keys.setter
    def user_ssh_keys(self, user_ssh_keys):
        """Sets the user_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.

        The UUIDs of users whose SSH keys should be included on the provisioned device.

        :param user_ssh_keys: The user_ssh_keys of this SpotMarketRequestCreateInputInstanceAttributes.
        :type user_ssh_keys: List[str]
        """

        self._user_ssh_keys = user_ssh_keys

    @property
    def userdata(self):
        """Gets the userdata of this SpotMarketRequestCreateInputInstanceAttributes.


        :return: The userdata of this SpotMarketRequestCreateInputInstanceAttributes.
        :rtype: str
        """
        return self._userdata

    @userdata.setter
    def userdata(self, userdata):
        """Sets the userdata of this SpotMarketRequestCreateInputInstanceAttributes.


        :param userdata: The userdata of this SpotMarketRequestCreateInputInstanceAttributes.
        :type userdata: str
        """

        self._userdata = userdata
