# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from metal.types.base_model_ import Model
from metal.types.spot_prices_per_baremetal import SpotPricesPerBaremetal
from metal import util


class SpotPricesPerNewFacility(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, baremetal_1e: SpotPricesPerBaremetal=None):
        """SpotPricesPerNewFacility - a model defined in OpenAPI

        :param baremetal_1e: The baremetal_1e of this SpotPricesPerNewFacility.
        """
        self.openapi_types = {
            'baremetal_1e': SpotPricesPerBaremetal
        }

        self.attribute_map = {
            'baremetal_1e': 'baremetal_1e'
        }

        self._baremetal_1e = baremetal_1e

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SpotPricesPerNewFacility':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SpotPricesPerNewFacility of this SpotPricesPerNewFacility.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def baremetal_1e(self):
        """Gets the baremetal_1e of this SpotPricesPerNewFacility.


        :return: The baremetal_1e of this SpotPricesPerNewFacility.
        :rtype: SpotPricesPerBaremetal
        """
        return self._baremetal_1e

    @baremetal_1e.setter
    def baremetal_1e(self, baremetal_1e):
        """Sets the baremetal_1e of this SpotPricesPerNewFacility.


        :param baremetal_1e: The baremetal_1e of this SpotPricesPerNewFacility.
        :type baremetal_1e: SpotPricesPerBaremetal
        """

        self._baremetal_1e = baremetal_1e
