# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from metal.apis.tag_to_api import tag_to_api

import enum


class TagValues(str, enum.Enum):
    AUTHENTICATION = "Authentication"
    ERRORS = "Errors"
    BATCHES = "Batches"
    BGP = "BGP"
    CAPACITY = "Capacity"
    INTERCONNECTIONS = "Interconnections"
    DEVICES = "Devices"
    EMAILS = "Emails"
    EVENTS = "Events"
    FACILITIES = "Facilities"
    GLOBAL_BGP_RANGES = "GlobalBgpRanges"
    HARDWARE_RESERVATIONS = "HardwareReservations"
    INCIDENTS = "Incidents"
    INVITATIONS = "Invitations"
    IPADDRESSES = "IPAddresses"
    LICENSES = "Licenses"
    MEMBERSHIPS = "Memberships"
    METADATA = "Metadata"
    METAL_GATEWAYS = "MetalGateways"
    METROS = "Metros"
    OPERATING_SYSTEMS = "OperatingSystems"
    ORGANIZATIONS = "Organizations"
    OTPS = "OTPs"
    PASSWORD_RESET_TOKENS = "PasswordResetTokens"
    PAYMENT_METHODS = "PaymentMethods"
    PLANS = "Plans"
    PORTS = "Ports"
    PROJECTS = "Projects"
    SELF_SERVICE_RESERVATIONS = "SelfServiceReservations"
    SPOT_MARKET = "SpotMarket"
    SSHKEYS = "SSHKeys"
    SUPPORT_REQUEST = "SupportRequest"
    TRANSFER_REQUESTS = "TransferRequests"
    TWO_FACTOR_AUTH = "TwoFactorAuth"
    USAGES = "Usages"
    USERDATA = "Userdata"
    USERS = "Users"
    USER_VERIFICATION_TOKENS = "UserVerificationTokens"
    VLANS = "VLANs"
    VOLUMES = "Volumes"
    VRFS = "VRFs"
